/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.watertank;

import javax.swing.JOptionPane;

/**
 *
 * @author CEHVAREE
 */
public class tankGUI extends javax.swing.JFrame {
    
    private Tank myTank;
    /**
     * Creates new form tankGUI
     */
    public tankGUI() {
        
        myTank = new Tank();
        
        initComponents();
        initValues();
        
        
    }
    
    private void initValues()
    {
        txtHeigth.setText(Double.toString(myTank.getHeight()));
        txtWidth.setText(Double.toString(myTank.getWidth()));
        txtLength.setText(Double.toString(myTank.getLength()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtHeigth = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank Volume");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });
        getContentPane().add(txtLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 60, -1));
        getContentPane().add(txtWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, -1));
        getContentPane().add(txtHeigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 60, -1));

        jLabel1.setText("Length:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel2.setText("Width");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel3.setText("Heigth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel4.setText("Volume");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
        getContentPane().add(txtVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, -1));

        jLabel5.setText("Area");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });
        getContentPane().add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 60, -1));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\cehvaree\\OneDrive - Eastern New Mexico University\\Java 2\\GUI Programming\\ch2\\cube.gif")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, -1));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLengthActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try
        {
            myTank.setHeight(Double.valueOf(txtHeigth.getText()));
            myTank.setLength(Double.valueOf(txtLength.getText()));
            myTank.setWidth(Double.valueOf(txtWidth.getText()));
            
            double volume  = myTank.getVolume();
            double area = myTank.getArea();
            
            txtVolume.setText(String.format("%.2f", volume));
            txtArea.setText(String.format("%.2f", area));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(tankGUI.this,"Incorrect number format");
        }
        
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        myTank.setHeight(0);
        myTank.setLength(0);
        myTank.setWidth(0);
        
        txtHeigth.setText(Double.toString(myTank.getHeight()));
        txtLength.setText(Double.toString(myTank.getLength()));
        txtWidth.setText(Double.toString(myTank.getWidth()));
        txtVolume.setText("");
        txtArea.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtHeigth;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtVolume;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
