/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fastfoodgui;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author CEHVAREE
 */
public class FastFoodGUI extends javax.swing.JFrame {
    
    private HashMap<String, Integer> buy = new HashMap<>();
    
    private FastFood myFF;
    /**
     * Creates new form FastFoodGUI
     */
    public FastFoodGUI() {
        
        myFF = new FastFood();
        initComponents();
        setPrices();
    }

    private void setPrices(){
        
        txtBurgerPrice.setText(Double.toString(myFF.getPrice("burger")));
        txtFriesPrice.setText(Double.toString(myFF.getPrice("fries")));
        txtSodaPrice.setText(Double.toString(myFF.getPrice("soda")));
        txtCakePrice.setText(Double.toString(myFF.getPrice("cake")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinBurger = new javax.swing.JSpinner();
        spinFries = new javax.swing.JSpinner();
        spinCake = new javax.swing.JSpinner();
        spinSoda = new javax.swing.JSpinner();
        btnTotal = new javax.swing.JButton();
        txtSubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        txtBurgerPrice = new javax.swing.JTextField();
        txtFriesPrice = new javax.swing.JTextField();
        txtSodaPrice = new javax.swing.JTextField();
        txtCakePrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fast Food");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fries.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burger.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/round-cake.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soda4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        spinBurger.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spinBurger.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        spinFries.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spinFries.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        spinCake.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spinCake.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        spinSoda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spinSoda.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        btnTotal.setText("Calculate Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        txtSubtotal.setEditable(false);
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 80, -1));

        jLabel5.setText("Subtotal    $");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel6.setText("Total          $");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 80, 20));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 110, -1));
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtBurgerPrice.setEditable(false);
        getContentPane().add(txtBurgerPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, -1));

        txtFriesPrice.setEditable(false);
        getContentPane().add(txtFriesPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 60, -1));

        txtSodaPrice.setEditable(false);
        getContentPane().add(txtSodaPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 60, -1));

        txtCakePrice.setEditable(false);
        getContentPane().add(txtCakePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 60, -1));

        jLabel7.setText("$");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel8.setText("$");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 20, -1));

        jLabel9.setText("$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel10.setText("$");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        setBounds(0, 0, 720, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        spinBurger.setValue(0);
        spinFries.setValue(0);
        spinSoda.setValue(0);
        spinCake.setValue(0);
        txtSubtotal.setText("");
        txtTotal.setText("");
        
        buy.clear();
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        
        // Calculate subtotal and Total
        // Get the values of spinners
        // Add them to the hashmap
        
        myFF.setSubtotal(0.0);
        myFF.setTotal(0.0);
        
        System.out.println(spinBurger.getValue());
        System.out.println(spinFries.getValue());
        System.out.println(spinSoda.getValue());
        System.out.println(spinCake.getValue());
        
        buy.put("burger", (Integer)spinBurger.getValue() );
        buy.put("fries", (Integer)spinFries.getValue() );
        buy.put("soda", (Integer)spinSoda.getValue() );
        buy.put("cake", (Integer)spinCake.getValue() );
        
        // Subtotal
        myFF.computeSubtotal(buy);
        txtSubtotal.setText(String.format("%.2f", myFF.getSubtotal()));
        
        // Total
        myFF.computeTotal();;
        txtTotal.setText(String.format("%.2f", myFF.getTotal()));
        
    }//GEN-LAST:event_btnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFoodGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JSpinner spinBurger;
    private javax.swing.JSpinner spinCake;
    private javax.swing.JSpinner spinFries;
    private javax.swing.JSpinner spinSoda;
    private javax.swing.JTextField txtBurgerPrice;
    private javax.swing.JTextField txtCakePrice;
    private javax.swing.JTextField txtFriesPrice;
    private javax.swing.JTextField txtSodaPrice;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
