/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculate;

import javax.swing.JOptionPane;

/**
 *
 * @author CEHVAREE
 */
public class calculate extends javax.swing.JFrame {
    
    double A, B, answer;
    /**
     * Creates new form calculate
     */
    public calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblA = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        lblB = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtAdd = new javax.swing.JTextField();
        btnSubtract = new javax.swing.JButton();
        txtSubtract = new javax.swing.JTextField();
        btnProduct = new javax.swing.JButton();
        txtProduct = new javax.swing.JTextField();
        btnDivide = new javax.swing.JButton();
        txtDivide = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblA.setText("A");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtA.setText("0.0");
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, -1));

        lblB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblB.setText("B");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtB.setText("0.0");
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, -1));

        btnAdd.setText("A + B = ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtAdd.setEditable(false);
        txtAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddFocusGained(evt);
            }
        });
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });
        getContentPane().add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 60, -1));

        btnSubtract.setText("A - B =");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtSubtract.setEditable(false);
        txtSubtract.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubtractFocusGained(evt);
            }
        });
        txtSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtractActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 60, -1));

        btnProduct.setText("A * B =");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtProduct.setEditable(false);
        txtProduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProductFocusGained(evt);
            }
        });
        getContentPane().add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 60, -1));

        btnDivide.setText("A / B =");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtDivide.setEditable(false);
        txtDivide.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDivideFocusGained(evt);
            }
        });
        getContentPane().add(txtDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 60, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        setBounds(0, 0, 283, 439);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       
        try
        {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A + B;
//            txtAdd.setText(Double.toString(answer));
            txtAdd.setText( String.format("%.2f", answer) );
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        try
        {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A - B;
//            txtSubtract.setText( Double.toString(answer) );
            txtSubtract.setText( String.format("%.2f", answer) );
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void txtSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtractActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        try
        {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            answer = A * B;
//            txtProduct.setText(Double.toString(answer));
            txtProduct.setText( String.format("%.2f", answer) );
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        try
        {
            A = Double.parseDouble(txtA.getText());
            B = Double.parseDouble(txtB.getText());
            
            if (B == 0.0 || B == 0)
            {
                JOptionPane.showMessageDialog(calculate.this, "Division by 0 is not allowed");
                answer = 0.0;
            }
            else
            {
                answer = A / B;
            }
            
//            txtDivide.setText(Double.toString(answer));
            txtDivide.setText( String.format("%.2f", answer) );
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddFocusGained
        
    }//GEN-LAST:event_txtAddFocusGained

    private void txtSubtractFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubtractFocusGained
        
    }//GEN-LAST:event_txtSubtractFocusGained

    private void txtProductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProductFocusGained
        
    }//GEN-LAST:event_txtProductFocusGained

    private void txtDivideFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDivideFocusGained
        
    }//GEN-LAST:event_txtDivideFocusGained

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtA.setText("0.0");
        txtB.setText("0.0");
        txtAdd.setText("");
        txtSubtract.setText("");
        txtProduct.setText("");
        txtDivide.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtDivide;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtSubtract;
    // End of variables declaration//GEN-END:variables
}
