/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tickets;

import javax.swing.JOptionPane;

/**
 *
 * @author CEHVAREE
 */
public class MainTickets extends javax.swing.JFrame {
    
    private static final double TICKET_COST = 8.2;
    private static final double CHILD_PERCENTAGE = 0.6;
    private static final double RETURN = 1.5;
    private static final double FIRST = 3.0;
    private static final double DISCOUNT = 0.10;
    /**
     * Creates new form MainTickets
     */
    public MainTickets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJourneytype = new javax.swing.ButtonGroup();
        btnClass = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAdult = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChildren = new javax.swing.JTextField();
        panelMiddle = new javax.swing.JPanel();
        rbSingle = new javax.swing.JRadioButton();
        rbReturn = new javax.swing.JRadioButton();
        panelClass = new javax.swing.JPanel();
        rbFirst = new javax.swing.JRadioButton();
        rbSecond = new javax.swing.JRadioButton();
        panelTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnIssue = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tickets");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Tickets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        panelTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Adults");

        jLabel3.setText("Children");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, 40));

        panelMiddle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMiddle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJourneytype.add(rbSingle);
        rbSingle.setSelected(true);
        rbSingle.setText("Single");
        panelMiddle.add(rbSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnJourneytype.add(rbReturn);
        rbReturn.setText("Return");
        panelMiddle.add(rbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        getContentPane().add(panelMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 50));

        panelClass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnClass.add(rbFirst);
        rbFirst.setText("First class");

        btnClass.add(rbSecond);
        rbSecond.setSelected(true);
        rbSecond.setText("Second class");

        javax.swing.GroupLayout panelClassLayout = new javax.swing.GroupLayout(panelClass);
        panelClass.setLayout(panelClassLayout);
        panelClassLayout.setHorizontalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(rbSecond)
                .addGap(54, 54, 54))
        );
        panelClassLayout.setVerticalGroup(
            panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFirst)
                    .addComponent(rbSecond))
                .addContainerGap())
        );

        getContentPane().add(panelClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, 40));

        panelTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Day Total of tickets issued:    $");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 210, 40));

        btnIssue.setText("Issue ticket");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        getContentPane().add(btnIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, -1));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
       int adult;
       int child;
       boolean returnWanted;
       boolean firstWanted;
       double ticketcost;
       
       try
       {
           // Adult tickets
           if (txtAdult.getText().equals(""))
           {
               adult = 0;
           }
           else
           {
               adult = Integer.parseInt(txtAdult.getText());
           }
           
           // Child tickets
           if (txtChildren.getText().equals(""))
           {
               child = 0;
           }
           else
           {
               child = Integer.parseInt(txtChildren.getText());
           }
           
           // Calculate the cost
           ticketcost = adult * TICKET_COST;
           ticketcost += child * TICKET_COST * CHILD_PERCENTAGE;
           
           if (rbReturn.isSelected())
           {
               returnWanted=true;
               ticketcost = ticketcost * RETURN;
           }
           else
           {
               returnWanted = false;
           }
           
           if (rbFirst.isSelected())
           {
               firstWanted=true;
               ticketcost = ticketcost + (adult+child)*FIRST;
           }
           else
           {
               firstWanted=false;
           }
           
           if ( (adult+child) >= 4)
           {
               ticketcost = ticketcost * (1-DISCOUNT);
           }
           
           Ticket.setAdult(adult);
           Ticket.setChild(child);
           Ticket.setReturnWanted(returnWanted);
           Ticket.setFirstWanted(firstWanted);
           Ticket.setTicketcost(ticketcost);
           
           if (ticketcost > 0)
           {
               // txtTotal.setText(String.format("%.2f", ticketcost));
                new displayTicket().setVisible(true);
           }

       }
       
       catch (NumberFormatException e)
       {
           JOptionPane.showMessageDialog(MainTickets.this, "Incorrect number format");
       }
       
       
    }//GEN-LAST:event_btnIssueActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtAdult.setText("");
        txtChildren.setText("");
        // txtTotal.setText("");
        
        rbSingle.setSelected(true);
        rbSecond.setSelected(true);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        String s = String.format("%.2f", Ticket.getDayTotal());
        txtTotal.setText(s);
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnClass;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnIssue;
    private javax.swing.ButtonGroup btnJourneytype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelClass;
    private javax.swing.JPanel panelMiddle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JRadioButton rbFirst;
    private javax.swing.JRadioButton rbReturn;
    private javax.swing.JRadioButton rbSecond;
    private javax.swing.JRadioButton rbSingle;
    private javax.swing.JTextField txtAdult;
    private javax.swing.JTextField txtChildren;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
